executor: pcluster-slurm
  #cluster-status: "/home/ubuntu/screening_workflow/slurm/status_squeue.sh"
jobs: 500
keep-going: true

  # g24   Small node;  2 CPUs; ~15G RAM; 1 GPU; max-count=100 (default)
  # g212  Mid node;    6 CPUs; ~47G RAM; 1 GPU; max-count=30
  # g232  Large node; 16 CPUs; ~127G RAM; 1 GPU; max-count=15


# Defaults for rules that omit them (can be overridden per-rule)
default-resources:
  - cpus_per_task=1
  - mem_mb=1600
  - runtime=600
  - slurm_extra="--partition=g24"

set-resources:
  prefold_af3:
    cpus_per_task: 16
    mem_mb: 64000
    slurm_extra: "--exclusive --partition=g232"

  prefold_boltz2:
    cpus_per_task: 16
    mem_mb: 64000
    slurm_extra: "--exclusive --partition=g232"

  vina:
    cpus_per_task: 1
    mem_mb: 1000
    runtime: 6000
    slurm_extra: "--partition=g24"

  af3:
    cpus_per_task: 4
    mem_mb: 1500
    runtime: 6000
    slurm_extra: "--exclusive --partition=g24"

  boltz2:
    cpus_per_task: 4
    mem_mb: 1500
    runtime: 6000
    slurm_extra: "--exclusive --partition=g24"

  diffdock:
    cpus_per_task: 4
    mem_mb: 1500
    runtime: 6000
    slurm_extra: "--exclusive --partition=g24"

  md:
    cpus_per_task: 16
    mem_mb: 15000
    runtime: 6000
    slurm_extra: "--exclusive --partition=g232"

  pbsa:
    cpus_per_task: 2
    mem_mb: 1000
    runtime: 6000
    slurm_extra: "--partition=g24"
